init: 
install:
  - cinst ActivePerl
  - cmd: where perl
  - cmd: perl --version
build_script: 
  - cmd: appveyor-build.cmd
test: off 
version: 0.0.1.{build} 
artifacts: 
  - path: Debug
    name: Debug
